---
- name: Install containerd dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Detect OS distribution
  set_fact:
    containerd_os: "{{ 'debian' if ansible_distribution == 'Debian' else 'ubuntu' }}"
    containerd_release: "{{ 'bullseye' if ansible_distribution_release == 'bookworm' else ansible_distribution_release }}"

- name: Add Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ containerd_os }}/gpg"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ containerd_os }} {{ containerd_release }} stable"
    state: present

- name: Install containerd
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate containerd config
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: restart containerd

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started
    daemon_reload: yes