# ---- etcd client certificates ----
- name: Render etcd client CSR (for apiserver)
  copy:
    dest: "{{ k8s_pki_etcd_dir }}/apiserver-etcd-client.json"
    mode: "0644"
    content: |
      { "CN":"kube-apiserver-etcd-client", "key":{"algo":"rsa","size":4096}, "names":[{"O":"system:masters"}] }

- name: Generate etcd client cert (for apiserver)
  shell: >
    cfssl gencert -ca=etcd-ca.pem -ca-key=etcd-ca-key.pem -config={{ k8s_pki_dir }}/ca-config.json -profile=client
    apiserver-etcd-client.json | cfssljson -bare apiserver-etcd-client
  args:
    chdir: "{{ k8s_pki_etcd_dir }}"
    creates: "{{ k8s_pki_etcd_dir }}/apiserver-etcd-client.pem"
  register: etcd_client_result
  failed_when: etcd_client_result is failed

- name: Render etcd healthcheck client CSR
  copy:
    dest: "{{ k8s_pki_etcd_dir }}/healthcheck-client.json"
    mode: "0644"
    content: |
      { "CN":"kube-etcd-healthcheck-client", "key":{"algo":"rsa","size":4096}, "names":[{"O":"system:masters"}] }

- name: Generate etcd healthcheck client cert
  shell: >
    cfssl gencert -ca=etcd-ca.pem -ca-key=etcd-ca-key.pem -config={{ k8s_pki_dir }}/ca-config.json -profile=client
    healthcheck-client.json | cfssljson -bare healthcheck-client
  args:
    chdir: "{{ k8s_pki_etcd_dir }}"
    creates: "{{ k8s_pki_etcd_dir }}/healthcheck-client.pem"
  register: etcd_healthcheck_result
  failed_when: etcd_healthcheck_result is failed