# ---- etcd per-node peer/server certs ----
- name: Render etcd node CSR JSON
  when: (cp_hosts | default([])) | length > 0
  template:
    src: etcd-node.json.j2
    dest: "{{ k8s_pki_etcd_dir }}/{{ item }}-csr.json"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ cp_hosts | default([]) }}"
  vars:
    node_ip: "{{ hostvars[item].private_ip }}"
    node_name: "{{ item }}"
    node_fqdn: "{{ item }}.{{ cluster_domain }}"

- name: Generate etcd node cert (peer/server profile)
  when: (cp_hosts | default([])) | length > 0
  shell: >
    cfssl gencert -ca=etcd-ca.pem -ca-key=etcd-ca-key.pem -config={{ k8s_pki_dir }}/ca-config.json -profile=peer
    {{ item }}-csr.json | cfssljson -bare {{ item }}
  args:
    chdir: "{{ k8s_pki_etcd_dir }}"
    creates: "{{ k8s_pki_etcd_dir }}/{{ item }}.pem"
  loop: "{{ cp_hosts | default([]) }}"
  register: etcd_peer_result
  failed_when: etcd_peer_result is failed