- import_tasks: set_fact.yml
  tags: [always]

- import_tasks: set_dir.yml
  tags: [always]

- import_tasks: ca_root.yml
  tags: [pki, ca, root_ca]

- import_tasks: ca_etcd.yml
  tags: [pki, ca, etcd_ca]

- import_tasks: ca_etcd_peer.yml
  tags: [pki, ca, etcd_peer]

- import_tasks: ca_etcd_client.yml
  tags: [pki, ca, etcd_client]

- import_tasks: ca_controlplane.yml
  tags: [pki, ca, controlplane]

- import_tasks: ca_frontproxy.yml
  tags: [pki, ca, frontproxy]

- import_tasks: service_account.yml
  tags: [pki, sa]

- import_tasks: rename_files.yml
  tags: [pki, rename]

- import_tasks: set_permissions.yml
  tags: [pki, permissions]