# ---- Service Account signing keys ----
- name: Generate SA private key
  shell: "openssl genrsa -out sa-key.pem 4096"
  args:
    chdir: "{{ k8s_pki_dir }}"
    creates: "{{ k8s_pki_dir }}/sa-key.pem"
  register: sa_key_result
  failed_when: sa_key_result is failed

- name: Generate SA public key
  shell: "openssl rsa -in sa-key.pem -pubout -out sa-pub.pem"
  args:
    chdir: "{{ k8s_pki_dir }}"
    creates: "{{ k8s_pki_dir }}/sa-pub.pem"
  register: sa_pub_result
  failed_when: sa_pub_result is failed

- name: Validate service account keys
  stat:
    path: "{{ item }}"
  register: sa_files
  failed_when: not sa_files.stat.exists
  loop:
    - "{{ k8s_pki_dir }}/sa-key.pem"
    - "{{ k8s_pki_dir }}/sa-pub.pem"