- name: Create pki directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  run_once: true
  changed_when: false
  loop:
    - "{{ k8s_pki_dir }}"
    - "{{ k8s_pki_etcd_dir }}"