---
- name: Ensure PKI and kubelet dirs exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ k8s_pki_dir }}"
    - "{{ kubelet_dir }}"

# You can copy the CA from controller host or distribute from Ansible controller
# Option A: pull from a controller host via delegate_to (requires SSH path)
# Option B (shown): ship from controller files/vars; here we assume it's available locally

# - name: Place cluster root CA (PEM)
#   become: true
#   ansible.builtin.copy:
#     src: ca.crt         # put ca.crt next to your play or use a role file path
#     dest: "{{ root_ca_file }}"
#     owner: root
#     group: root
#     mode: "0644"

- name: Render bootstrap kubeconfig
  become: true
  ansible.builtin.template:
    src: bootstrap-kubeconfig.j2
    dest: "{{ kubelet_bootstrap_kubeconfig }}"
    owner: root
    group: root
    mode: "0600"

- name: Start kubelet (auto-join will begin)
  become: true
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
