---
- name: Set certificate ownership for etcd
  file:
    path: "{{ etcd_cert_dir }}/{{ inventory_hostname }}.pem"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: "0644"

- name: Set private key ownership for etcd
  file:
    path: "{{ etcd_cert_dir }}/{{ inventory_hostname }}-key.pem"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: "0600"

- name: Set CA certificate ownership
  file:
    path: "{{ etcd_ca_file }}"
    owner: root
    group: root
    mode: "0644"

- name: Generate etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: "0644"
  notify:
    - reload systemd
    - restart etcd