- name: Generate etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: "0644"
  notify:
    - reload systemd
    - restart etcd


- name: Set etcd environment variables
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    state: present
  loop:
    - "ETCDCTL_API=3"
    - "ETCDCTL_CACERT={{ etcd_ca_file }}"
    - "ETCDCTL_CERT={{ etcd_cert_dir }}/server.crt"
    - "ETCDCTL_KEY={{ etcd_cert_dir }}/server.key"
    - "ETCDCTL_WRITE_OUT=table"
- name: set ETCDCTL_ENDPOINTS
  lineinfile:
    path: /etc/environment
    line: "ETCDCTL_ENDPOINTS={{ etcd_endpoints }}"
    state: present
  