---
- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_config_dir }}"

- name: Download and extract etcd
  unarchive:
    src: "{{ etcd_download_url }}"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/etcd-v{{ etcd_version }}-linux-amd64"

- name: Install etcd binaries
  copy:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "{{ etcd_bin_dir }}/{{ item }}"
    mode: "0755"
    remote_src: yes
  loop:
    - etcd
    - etcdctl
  notify: restart etcd