---
- name: Import installation tasks
  import_tasks: install.yml
  tags: [etcd, install]

- name: Import CLI installation tasks
  hosts: jumpbox
  import_tasks: install_cli.yml
  tags: [etcd, install_cli]

- name: Import configuration tasks
  import_tasks: configure.yml
  tags: [etcd, configure]

- name: Import service tasks
  import_tasks: service.yml
  tags: [etcd, service]

- name: Import fact setting tasks
  import_tasks: set_fact.yml
  tags: [etcd, set_fact]