---
- name: Start and enable etcd service
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for etcd to be ready
  uri:
    url: "https://{{ private_ip }}:{{ etcd_client_port }}/health"
    method: GET
    validate_certs: no
    client_cert: "{{ etcd_cert_dir }}/{{ inventory_hostname }}.pem"
    client_key: "{{ etcd_cert_dir }}/{{ inventory_hostname }}-key.pem"
  register: etcd_health
  until: etcd_health.status == 200
  delegate_to: jumpbox
  retries: 30
  delay: 5

# - name: Verify etcd cluster health
#   shell: |
#     ETCDCTL_API=3 {{ etcd_bin_dir }}/etcdctl \
#       --endpoints=https://{{ private_ip }}:{{ etcd_client_port }} \
#       --cacert={{ etcd_ca_file }} \
#       --cert={{ etcd_cert_dir }}/{{ inventory_hostname }}.pem \
#       --key={{ etcd_cert_dir }}/{{ inventory_hostname }}-key.pem \
#       endpoint health
#   register: etcd_cluster_health
#   delegate_to: jumpbox
#   changed_when: false

# - name: Display etcd cluster status
#   debug:
#     msg: "{{ etcd_cluster_health.stdout_lines }}"