- name: Copy the certificate to the control plane
  synchronize:
    src: "{{ item }}.pem"
    dest: "{{ item }}.crt"
    mode: push
  delegate_to: jumpbox
  loop:
    - "{{k8s_pki_etcd_dir}}/admin"
    - "{{k8s_pki_etcd_dir}}/controller-manager"
    - "{{k8s_pki_etcd_dir}}/kube-apiserver"
    - "{{k8s_pki_etcd_dir}}/kube-controller-manager"
    - "{{k8s_pki_etcd_dir}}/front-proxy-ca"
    - "{{k8s_pki_etcd_dir}}/front-proxy-client"
    - "{{k8s_pki_etcd_dir}}/apiserver-kubelet"
    - "{{k8s_pki_etcd_dir}}/kube-scheduler"

- name: Copy the keys to the control plane
  synchronize:
    src: "{{ item }}.key"
    dest: "{{ item }}.key"
    mode: push
  delegate_to: jumpbox
  loop:
    - "{{k8s_pki_etcd_dir}}/admin"
    - "{{k8s_pki_etcd_dir}}/controller-manager"
    - "{{k8s_pki_etcd_dir}}/kube-apiserver"
    - "{{k8s_pki_etcd_dir}}/kube-controller-manager"
    - "{{k8s_pki_etcd_dir}}/front-proxy-ca"
    - "{{k8s_pki_etcd_dir}}/front-proxy-client"
    - "{{k8s_pki_etcd_dir}}/apiserver-kubelet"
    - "{{k8s_pki_etcd_dir}}/kube-scheduler"
