- name: Generate Kubernetes PKI on jumpbox
  hosts: jumpbox
  become: true
  tags:
    - pki
    - pki_generate
  roles:
    - pki_generate

- name: Distribute PKI to control planes
  hosts: control_plane
  become: true
  gather_facts: false
  tags:
    - pki
    - pki_distribute
  roles:
    - pki_distribute
