---
# Generate kubeconfig files for control plane components
- name: Generate controller-manager kubeconfig
  template:
    src: controller-manager.conf.j2
    dest: "{{ kubernetes_config_dir }}/controller-manager.conf"
    mode: "0600"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
  when: cert_dir + '/kube-controller-manager.crt' is file

- name: Generate scheduler kubeconfig
  template:
    src: scheduler.conf.j2
    dest: "{{ kubernetes_config_dir }}/scheduler.conf"
    mode: "0600"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
  when: cert_dir + '/kube-scheduler.crt' is file