---
- name: Render custom /etc/hosts file
  become: yes
  ansible.builtin.template:
    src: templates/etc-hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: yes
