---
- name: restart kube-apiserver
  systemd:
    name: kube-apiserver
    state: restarted
  listen: "restart kube-apiserver"

- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
  listen: "restart kube-controller-manager"

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
  listen: "restart kube-scheduler"

- name: reload systemd
  systemd:
    daemon_reload: yes
  listen: "reload systemd"