---
- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
  listen: "restart etcd"

- name: reload systemd
  systemd:
    daemon_reload: yes
  listen: "reload systemd"